name: nb2html

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install nbconvert
        run: pip install nbconvert

      - name: Convert all .ipynb files to html
        run: find . -name '*.ipynb' -type f -execdir jupyter nbconvert --template classic --to html {} \;
        
      - name: Commit updated notebook
        uses: EndBug/add-and-commit@v9.1.4
        with:
          author_name: github-actions
          message: "Translate Jupyter Notebook to HTML"
          add: "notebooks/*.html"